[package]
name = "rust_hello"
version = "0.1.0"
authors = ["wangyong95 <wangyong95@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
